# Generated by Django 3.0.4 on 2020-03-24 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='activePosts',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='activeStory',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='firstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='follower',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='follower',
            name='lastPost',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='lastStory',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='insta_manager.UserInstagram'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='picture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userinstagram',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ig', to=settings.AUTH_USER_MODEL),
        ),
    ]
