# Generated by Django 3.0.4 on 2020-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_manager', '0002_auto_20200324_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='activePosts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='activeStory',
            field=models.BooleanField(default=True),
        ),
    ]
