# Generated by Django 3.0.8 on 2020-07-21 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta_manager', '0003_auto_20200324_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploadedAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userinstagram',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True)),
                ('firstName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('picture', models.CharField(blank=True, max_length=100)),
                ('activeStory', models.BooleanField(default=True)),
                ('activePosts', models.BooleanField(default=True)),
                ('lastPost', models.DateTimeField(auto_now_add=True)),
                ('lastStory', models.DateTimeField(auto_now_add=True)),
                ('followedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='insta_manager.UserInstagram')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='insta_manager.Friend'),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
