# Generated by Django 3.0.8 on 2020-07-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_manager', '0004_auto_20200721_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='lastName',
        ),
        migrations.AddField(
            model_name='friend',
            name='fullName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='friend',
            name='activePosts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friend',
            name='activeStory',
            field=models.BooleanField(default=False),
        ),
    ]
