# Generated by Django 3.0.4 on 2020-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_manager', '0006_auto_20200726_1841'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('owner', 'uploadedAt'), name='unique post'),
        ),
    ]
