# Generated by Django 3.0.4 on 2020-11-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_manager', '0007_auto_20201031_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstagram',
            name='picture',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
